---
title: "Data Prep"
output: html_document
date: '2022-05-02'
---

```{r}

library(dplyr)
library(tidyverse)
library(ggvis)
library(cluster)

dow_jones_index_raw <- read.csv("/cloud/project/StockPicker/dow_jones_index.data")
dow_jones_index <- na.omit(dow_jones_index_raw)
dow_jones_index <- dow_jones_index %>% filter(date < '4/1/2011')
dow_jones_index <- subset(dow_jones_index, select = -c(quarter, stock, date, open, high, low, close, volume, previous_weeks_volume, next_weeks_open, next_weeks_close, percent_change_next_weeks_price ))


dow_jones_index_stocks <- unique(dow_jones_index$stock)
```

```{r}
sum_of_squares = kmeans(dow_jones_index, centers=1)$tot.withinss

for (i in 2:15)
  sum_of_squares[i] = kmeans(dow_jones_index, centers=i)$tot.withinss

sum_of_squares
```

```{r}
library(ggvis)

sum_of_squares_df = data.frame(c(1:15), c(sum_of_squares))
names(sum_of_squares_df)[1] = "Clusters"
names(sum_of_squares_df)[2] = "SS"

sum_of_squares_df

sum_of_squares_df %>%
  ggvis(~Clusters, ~SS) %>%
  layer_points(fill := "blue") %>%
  layer_lines() %>%
  set_options(height = 300, width = 400)
```

```{r}
clusters = kmeans(dow_jones_index, 8)
clusters

clusplot(dow_jones_index, clusters$cluster)
```
}}
